version: '3.8'

services:
  apache:
    build:
      context: .
    container_name: apache-server
    restart: unless-stopped
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - "${PROJECT_PATH}:/var/www/html"
    networks:
      - general-net

  db:
    image: mariadb:10.11
    container_name: db-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - general-net

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-server
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER: "${MYSQL_USER}"
      PMA_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      - db
    networks:
      - general-net

volumes:
  db-data:

networks:
  general-net:
    driver: bridge